### ISSUE TITLE
Investigate random NPE in test_entitlement_change_skip_phase

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-integration-tests#15]
See https://circleci.com/gh/killbill/killbill/738:

```
Error: test_change_multiple_times_over_initial_trial_period_1(KillBillIntegrationTests::TestEntitlementChangeSkipPhase)
  KillBillClient::API::InternalServerError: {"className":"org.skife.jdbi.v2.exceptions.CallbackFailedException","code":null,"message":"java.lang.NullPointerException","causeClassName":"java.lang.NullPointerException","causeMessage":null,"stackTrace":[]}
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/net_http_adapter.rb:217:in `request'
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/api.rb:55:in `put'
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/models/resource.rb:53:in `put'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:34:in `change_plan_with_target_phase'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:137:in `test_change_multiple_times_over_initial_trial_period_1'
     134:       # Change plan to Gold : NO TRIAL
     135:       requested_date = nil
     136:       billing_policy = "IMMEDIATE"
  => 137:       bp = bp.change_plan_with_target_phase({:productName => 'Gold', :billingPeriod => 'MONTHLY', :priceList => 'DEFAULT'}, @user, nil, nil, requested_date, billing_policy, :EVERGREEN, false, @options)
     138:       check_entitlement(bp, 'Gold', 'BASE', 'MONTHLY', 'DEFAULT', KB_INIT_DATE, nil)
     139:       wait_for_expected_clause(4, @account, @options, &@proc_account_invoices_nb)
     140: 
===============================================================================
E
===============================================================================
Error: test_change_multiple_times_over_initial_trial_period_2(KillBillIntegrationTests::TestEntitlementChangeSkipPhase)
  KillBillClient::API::InternalServerError: {"className":"org.skife.jdbi.v2.exceptions.CallbackFailedException","code":null,"message":"java.lang.NullPointerException","causeClassName":"java.lang.NullPointerException","causeMessage":null,"stackTrace":[]}
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/net_http_adapter.rb:217:in `request'
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/api.rb:55:in `put'
/var/lib/jruby/lib/ruby/gems/shared/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/models/resource.rb:53:in `put'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:34:in `change_plan_with_target_phase'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:223:in `test_change_multiple_times_over_initial_trial_period_2'
     220:       # Change plan to Gold : NO TRIAL
     221:       requested_date = nil
     222:       billing_policy = "IMMEDIATE"
  => 223:       bp = bp.change_plan_with_target_phase({:productName => 'Gold', :billingPeriod => 'MONTHLY', :priceList => 'DEFAULT'}, @user, nil, nil, requested_date, billing_policy, :EVERGREEN, false, @options)
     224:       check_entitlement(bp, 'Gold', 'BASE', 'MONTHLY', 'DEFAULT', KB_INIT_DATE, nil)
     225:       wait_for_expected_clause(4, @account, @options, &@proc_account_invoices_nb)
     226: 
===============================================================================
.........................................................................

Finished in 995.112 seconds.

132 tests, 7379 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
98.4848% passed
```

**Comment by pierre** [comment]
Another one:

```
Loaded suite /home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader
Started
.........................................................E
===============================================================================
Error: test_change_multiple_times_over_initial_trial_period_1(KillBillIntegrationTests::TestEntitlementChangeSkipPhase)
  KillBillClient::API::InternalServerError: {"className":"org.skife.jdbi.v2.exceptions.CallbackFailedException","code":null,"message":"java.lang.NullPointerException","causeClassName":"java.lang.NullPointerException","causeMessage":null,"stackTrace":[]}
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/net_http_adapter.rb:217:in `request'
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/api.rb:55:in `put'
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/models/resource.rb:53:in `put'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:34:in `change_plan_with_target_phase'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:137:in `test_change_multiple_times_over_initial_trial_period_1'
     134:       # Change plan to Gold : NO TRIAL
     135:       requested_date = nil
     136:       billing_policy = "IMMEDIATE"
  => 137:       bp = bp.change_plan_with_target_phase({:productName => 'Gold', :billingPeriod => 'MONTHLY', :priceList => 'DEFAULT'}, @user, nil, nil, requested_date, billing_policy, :EVERGREEN, false, @options)
     138:       check_entitlement(bp, 'Gold', 'BASE', 'MONTHLY', 'DEFAULT', KB_INIT_DATE, nil)
     139:       wait_for_expected_clause(4, @account, @options, &@proc_account_invoices_nb)
     140: 
===============================================================================
E
===============================================================================
Error: test_change_multiple_times_over_initial_trial_period_2(KillBillIntegrationTests::TestEntitlementChangeSkipPhase)
  KillBillClient::API::InternalServerError: {"className":"org.skife.jdbi.v2.exceptions.CallbackFailedException","code":null,"message":"java.lang.NullPointerException","causeClassName":"java.lang.NullPointerException","causeMessage":null,"stackTrace":[]}
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/net_http_adapter.rb:217:in `request'
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/api/api.rb:55:in `put'
/home/killbill/killbill-integration-tests/vendor/bundle/ruby/2.4.0/bundler/gems/killbill-client-ruby-c0071f72fc10/lib/killbill_client/models/resource.rb:53:in `put'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:34:in `change_plan_with_target_phase'
/home/killbill/killbill-integration-tests/killbill-integration-tests/core/test_entitlement_change_skip_phase.rb:223:in `test_change_multiple_times_over_initial_trial_period_2'
     220:       # Change plan to Gold : NO TRIAL
     221:       requested_date = nil
     222:       billing_policy = "IMMEDIATE"
  => 223:       bp = bp.change_plan_with_target_phase({:productName => 'Gold', :billingPeriod => 'MONTHLY', :priceList => 'DEFAULT'}, @user, nil, nil, requested_date, billing_policy, :EVERGREEN, false, @options)
     224:       check_entitlement(bp, 'Gold', 'BASE', 'MONTHLY', 'DEFAULT', KB_INIT_DATE, nil)
     225:       wait_for_expected_clause(4, @account, @options, &@proc_account_invoices_nb)
     226: 
===============================================================================
.........................................................................

Finished in 1078.964530084 seconds.

132 tests, 7379 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
98.4848% passed

0.12 tests/s, 6.84 assertions/s
```

See https://circleci.com/gh/killbill/killbill/1186.

**Comment by pierre** [comment]
We now have the server-side logs available in CircleCI.

From https://circleci.com/gh/killbill/killbill/1475#artifacts/containers/0:

```
2018-04-13T15:11:19,171+0000 lvl='INFO', log='LoggingFilter', th='qtp671536858-72', xff='', rId='98245094-ddcd-4e42-889f-20cea967a806', tok='', aRId='', tRId='58', 1290 * Server in-bound request
1290 > PUT http://127.0.0.1:8080/1.0/kb/subscriptions/abfdb940-2051-4ce1-8d7b-1ba963e7bff5?callCompletion=false&billingPolicy=IMMEDIATE
1290 > Authorization: **************************
1290 > X-Killbill-Apikey: test-api-key1523632275-91793
1290 > Accept: application/json
1290 > X-Killbill-Apisecret: *******************************
1290 > User-Agent: killbill/1.12.1; ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
1290 > Host: 127.0.0.1:8080
1290 > Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
1290 > X-Killbill-Createdby: test_change_multiple_times_over_initial_trial_
1290 > Content-Length: 191
1290 > Content-Type: application/json
1290 > 

2018-04-13T15:11:19,180+0000 lvl='INFO', log='DefaultEntitlement', th='qtp671536858-72', xff='', rId='98245094-ddcd-4e42-889f-20cea967a806', tok='', aRId='58', tRId='58', Change Entitlement Plan:  id = 'abfdb940-2051-4ce1-8d7b-1ba963e7bff5', product='Gold', billingPeriod='MONTHLY', priceList='MONTHLY', overrides='[(spec=Gold:MONTHLY:EVERGREEN:DEFAULT:null:null:null:null)]', actionPolicy='IMMEDIATE'
2018-04-13T15:11:19,197+0000 lvl='WARN', log='LoggingResponse', th='qtp671536858-72', xff='', rId='98245094-ddcd-4e42-889f-20cea967a806', tok='98245094-ddcd-4e42-889f-20cea967a806', aRId='58', tRId='58', Internal error
org.skife.jdbi.v2.exceptions.CallbackFailedException: java.lang.NullPointerException
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:301)
	at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:324)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreateOverridePlanDefinition(DefaultCatalogOverrideDao.java:69)
	at org.killbill.billing.catalog.override.DefaultPriceOverride.getOrCreateOverriddenPlan(DefaultPriceOverride.java:124)
	at org.killbill.billing.catalog.StandaloneCatalogWithPriceOverride.createOrFindCurrentPlan(StandaloneCatalogWithPriceOverride.java:82)
	at org.killbill.billing.catalog.VersionedCatalog.createOrFindPlan(VersionedCatalog.java:311)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getDryRunChangePlanEffectiveDate(DefaultSubscriptionInternalApi.java:601)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$7.doCall(DefaultEntitlement.java:774)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$7.doCall(DefaultEntitlement.java:765)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:97)
	at org.killbill.billing.entitlement.api.DefaultEntitlement.changePlanOverrideBillingPolicy(DefaultEntitlement.java:804)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$8.doOperation(SubscriptionResource.java:592)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$8.doOperation(SubscriptionResource.java:566)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:839)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.changeEntitlementPlan(SubscriptionResource.java:615)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:111)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreatePhaseDefinitionFromTransactionWithoutUsageOverrides(DefaultCatalogOverrideDao.java:168)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreateOverridePhaseDefinitionFromTransaction(DefaultCatalogOverrideDao.java:128)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.access$000(DefaultCatalogOverrideDao.java:45)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao$1.inTransaction(DefaultCatalogOverrideDao.java:78)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao$1.inTransaction(DefaultCatalogOverrideDao.java:69)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:60)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:328)
	at org.skife.jdbi.v2.DBI$5.withHandle(DBI.java:328)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:298)
	... 83 common frames omitted
2018-04-13T15:11:19,198+0000 lvl='INFO', log='LoggingFilter', th='qtp671536858-72', xff='', rId='98245094-ddcd-4e42-889f-20cea967a806', tok='98245094-ddcd-4e42-889f-20cea967a806', aRId='58', tRId='58', 1290 * Server out-bound response
1290 < 500
1290 < Content-Type: application/json
1290 < 
```

```
2018-04-13T15:11:23,582+0000 lvl='INFO', log='LoggingFilter', th='qtp671536858-49', xff='', rId='2f2474af-5090-4c00-8259-33c308dd1fe3', tok='', aRId='', tRId='59', 1313 * Server in-bound request
1313 > PUT http://127.0.0.1:8080/1.0/kb/subscriptions/38e73f58-338d-4cdf-8b0f-037a49d87ffc?callCompletion=false&billingPolicy=IMMEDIATE
1313 > Authorization: **************************
1313 > X-Killbill-Apikey: test-api-key1523632279-795217
1313 > Accept: application/json
1313 > X-Killbill-Apisecret: ********************************
1313 > User-Agent: killbill/1.12.1; ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
1313 > Host: 127.0.0.1:8080
1313 > Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
1313 > X-Killbill-Createdby: test_change_multiple_times_over_initial_trial_
1313 > Content-Length: 191
1313 > Content-Type: application/json
1313 > 

2018-04-13T15:11:23,589+0000 lvl='INFO', log='DefaultEntitlement', th='qtp671536858-49', xff='', rId='2f2474af-5090-4c00-8259-33c308dd1fe3', tok='', aRId='59', tRId='59', Change Entitlement Plan:  id = '38e73f58-338d-4cdf-8b0f-037a49d87ffc', product='Gold', billingPeriod='MONTHLY', priceList='MONTHLY', overrides='[(spec=Gold:MONTHLY:EVERGREEN:DEFAULT:null:null:null:null)]', actionPolicy='IMMEDIATE'
2018-04-13T15:11:23,597+0000 lvl='WARN', log='LoggingResponse', th='qtp671536858-49', xff='', rId='2f2474af-5090-4c00-8259-33c308dd1fe3', tok='2f2474af-5090-4c00-8259-33c308dd1fe3', aRId='59', tRId='59', Internal error
org.skife.jdbi.v2.exceptions.CallbackFailedException: java.lang.NullPointerException
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:301)
	at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:324)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreateOverridePlanDefinition(DefaultCatalogOverrideDao.java:69)
	at org.killbill.billing.catalog.override.DefaultPriceOverride.getOrCreateOverriddenPlan(DefaultPriceOverride.java:124)
	at org.killbill.billing.catalog.StandaloneCatalogWithPriceOverride.createOrFindCurrentPlan(StandaloneCatalogWithPriceOverride.java:82)
	at org.killbill.billing.catalog.VersionedCatalog.createOrFindPlan(VersionedCatalog.java:311)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getDryRunChangePlanEffectiveDate(DefaultSubscriptionInternalApi.java:601)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$7.doCall(DefaultEntitlement.java:774)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$7.doCall(DefaultEntitlement.java:765)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:97)
	at org.killbill.billing.entitlement.api.DefaultEntitlement.changePlanOverrideBillingPolicy(DefaultEntitlement.java:804)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$8.doOperation(SubscriptionResource.java:592)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$8.doOperation(SubscriptionResource.java:566)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:839)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.changeEntitlementPlan(SubscriptionResource.java:615)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:111)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreatePhaseDefinitionFromTransactionWithoutUsageOverrides(DefaultCatalogOverrideDao.java:168)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.getOrCreateOverridePhaseDefinitionFromTransaction(DefaultCatalogOverrideDao.java:128)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao.access$000(DefaultCatalogOverrideDao.java:45)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao$1.inTransaction(DefaultCatalogOverrideDao.java:78)
	at org.killbill.billing.catalog.dao.DefaultCatalogOverrideDao$1.inTransaction(DefaultCatalogOverrideDao.java:69)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:60)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:328)
	at org.skife.jdbi.v2.DBI$5.withHandle(DBI.java:328)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:298)
	... 83 common frames omitted
2018-04-13T15:11:23,598+0000 lvl='INFO', log='LoggingFilter', th='qtp671536858-49', xff='', rId='2f2474af-5090-4c00-8259-33c308dd1fe3', tok='2f2474af-5090-4c00-8259-33c308dd1fe3', aRId='59', tRId='59', 1313 * Server out-bound response
1313 < 500
1313 < Content-Type: application/json
1313 < 
```

**Comment by pierre** [comment]
Tentative fix: https://github.com/killbill/killbill/commit/1b2a0a15affce3cc8f8f9f4ca0780f644aa3227b.

**Comment by pierre** [comment]
Unable to reproduce.
