### ISSUE TITLE
Running tests - KillBillClient::API::Unauthorized

### ISSUE THREAD

**Issue by roma-guru** [killbill/killbill-integration-tests#4]
Sorry, I'm complete novice to Ruby and can't figure out where to put _api_secret & api_key_ in test_base.rb.
I've launched KillBill from repo:

> ./bin/start-server -s -d -p 8181 > /tmp/server.out 2>&1 < /dev/null &

Here is what I've got on every test (_rake test:core_)

> Error: test_create_subscription_with_tz_plus_9_with_requested_date_today(KillBillIntegrationTests::TestWithDatesAndTimezones)
>   KillBillClient::API::Unauthorized: 
> /home/roma/.rvm/gems/jruby-1.7.24/gems/killbill-client-0.29.0/lib/killbill_client/api/net_http_adapter.rb:194:in `request'
> /home/roma/.rvm/gems/jruby-1.7.24/gems/killbill-client-0.29.0/lib/killbill_client/api/api.rb:49:in`post'
> /home/roma/.rvm/gems/jruby-1.7.24/gems/killbill-client-0.29.0/lib/killbill_client/models/resource.rb:45:in `post'
> /home/roma/.rvm/gems/jruby-1.7.24/gems/killbill-client-0.29.0/lib/killbill_client/models/tenant.rb:99:in`create'
> /home/roma/Projects/Github/KillBill/killbill-integration-tests/killbill-integration-tests/mixin-utils/helper.rb:78:in `setup_create_tenant'
> /home/roma/Projects/Github/KillBill/killbill-integration-tests/killbill-integration-tests/test_base.rb:42:in`setup_base'
> /home/roma/Projects/Github/KillBill/killbill-integration-tests/killbill-integration-tests/core/test_with_dates_timezones.rb:62:in `test_scenario_fixed_price_with_future_invoice'
> /home/roma/Projects/Github/KillBill/killbill-integration-tests/killbill-integration-tests/core/test_with_dates_timezones.rb:56:in`test_scenario_fixed_price'
> /home/roma/Projects/Github/KillBill/killbill-integration-tests/killbill-integration-tests/core/test_with_dates_timezones.rb:43:in `test_create_subscription_with_tz_plus_9_with_requested_date_today'
>      40: 
>      41:     def test_create_subscription_with_tz_plus_9_with_requested_date_today
>      42:       #  Requested date of '2013-08-03'  will take today's date (and all conversion in account timezone will lead to '2013-08-03' and NOT '2013-08-02')
>   => 43:       test_scenario_fixed_price("2013-08-02T18:00:00.000Z", 'Asia/Tokyo', '2013-08-03', '2013-08-03', '2013-08-03')
>      44:     end
>      45: 
>      46:     def test_create_subscription_with_tz_plus_9_with_requested_date_in_slight_past

**Comment by pierre** [comment]
A unique tenant will be created for each test, you shouldn't have to set them up.

Are you using the default credentials to talk to Kill Bill (admin/password)? Otherwise, you can configure them with [environment variables](https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/test_base.rb#L37).

**Comment by pierre** [comment]
Closing for lack of activity.
